//go:build darwin && amd64

// This file generated by cmd/gen/main.go - DO NOT EDIT

package release

import (
	_ "embed"
)

const (
	Target  = "darwin"
	Arch    = "amd64"
	Version = "14.5.0"
	Sha256  = "053246202f0b1782629250da781e21130e26d61d0ac50cf17b3317faafe88429"

	InitdbBinary   = "bin/initdb"
	PgCliBinary    = "bin/pg_ctl"
	PostgresBinary = "bin/postgres"
)

var (
	//go:embed postgres-darwin-amd64-14.5.0.tar.xz
	Archive []byte
)
