//go:build linux && amd64

// This file generated by cmd/gen/main.go - DO NOT EDIT

package release

import (
	_ "embed"
)

const (
	Target  = "linux"
	Arch    = "amd64"
	Version = "14.5.0"
    Sha256  = "3f379126fbda79f36b61aa1adc25ad5b797b0c0f32d9143da3fee8261689b9a4"

	InitdbBinary = "bin/initdb"
	PgCliBinary  = "bin/pg_ctl"
	PostgresBinary = "bin/postgres"
)

var (
	//go:embed postgres-linux-amd64-14.5.0.tar.xz
	Archive []byte
)


