//go:build linux && 386

// This file generated by cmd/gen/main.go - DO NOT EDIT

package release

import (
	_ "embed"
)

const (
	Target  = "linux"
	Arch    = "386"
	Version = "14.5.0"
	Sha256  = "0e6677e916c928b6b2d28e5f9a1088dcffa734463a3f14aa619431d0486ea109"

	InitdbBinary   = "bin/initdb"
	PgCliBinary    = "bin/pg_ctl"
	PostgresBinary = "bin/postgres"
)

var (
	//go:embed postgres-linux-386-14.5.0.tar.xz
	Archive []byte
)
