//go:build linux && arm64

// This file generated by cmd/gen/main.go - DO NOT EDIT

package release

import (
	_ "embed"
)

const (
	Target  = "linux"
	Arch    = "arm64"
	Version = "14.5.0"
	Sha256  = "272573684fcd38e89bd2bb2cf8abe910ede18a99ebdf9a070fb7b6e7fb89591a"

	InitdbBinary   = "bin/initdb"
	PgCliBinary    = "bin/pg_ctl"
	PostgresBinary = "bin/postgres"
)

var (
	//go:embed postgres-linux-arm64-14.5.0.tar.xz
	Archive []byte
)
